apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  user: cG9zdGdyZXM=          # postgres en base64
  password: UEBzc3dvcmQwMQ==  # your_password en base64

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi