apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Taille ajustable selon vos besoins
  storageClassName: standard  # Utilise la classe de stockage par défaut de Minikube