apiVersion: v1
kind: Service
metadata:
  name: employee-api
spec:
  type: NodePort
  selector:
    app: employee-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000