apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-employee
  template:
    metadata:
      labels:
        app: db-employee
    spec:
      containers:
      - name: db-employee
        image: postgres:17-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: POSTGRES_DB
          value: "employee_void_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc